name: Create S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  # Set your desired AWS region

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket --bucket Iam_s3_bucket222  --region us-east-1
