on:
  workflow_dispatch:
    inputs:
      ami_id:
        description: 'ami-067d1e60475437da2'
        required: true
      instance_type:
        description: 't2.micro'
        required: true
      key_name:
        description: 'jan2023'
        required: true

jobs:
  create-ec2:
    name: Create EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ${{ github.event.inputs.ami_id }} \
            --instance-type ${{ github.event.inputs.instance_type }} \
            --key-name ${{ github.event.inputs.key_name }}
