name: Create EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws configure set region us-east-1

      - name: Create EC2 Instance
        run: |
          # Use AWS CLI to create EC2 instances
          aws ec2 run-instances \
            --image-id ami-041feb57c611358bd \
            --instance-type t2.micro \
            --key-name jan2023
